$:.push File.expand_path("../lib", __FILE__)

# Maintain your gem's version:
require "slactionmailer/version"

# Describe your gem and declare its dependencies:
Gem::Specification.new do |s|
  s.name        = "slactionmailer"
  s.version     = Slactionmailer::VERSION
  s.authors     = ["Lee Gillentine"]
  s.email       = ["lee@fishburd.com"]
  s.homepage    = "https://github.com/geetotes/slactionmailer"
  s.summary     = "A drop in replacement for ActionMailer that sends your emails to a Slack channel"
  s.description = "Want to send the emails generated by your Ruby on Rails application to a Slack channel? Now you can!"
  s.license     = "MIT"

  s.files = Dir["{app,config,db,lib}/**/*", "MIT-LICENSE", "Rakefile", "README.rdoc"]
  s.test_files = Dir["test/**/*"]

  s.add_dependency "rails", "~> 4.2.2"
  s.add_dependency "slack-notifier"
  s.add_development_dependency 'rspec'
  s.add_development_dependency 'mail'


  s.add_development_dependency "sqlite3"
end
